[package]
name = "version_compare_poc"
version = "0.1.0"
authors = ["Tales Viegas <selatotal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
version-compare = "0.0.11"
