[package]
name = "diesel_demo"
version = "0.1.0"
authors = ["Tales Bitelo Viegas <selatotal@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.4", features = ["sqlite"]}
dotenv = "0.15.0"